import './globals.css';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { CustomThemeProvider } from '@/src/contexts/CustomThemeContext';
import Header from '@/src/components/Header';
import Footer from '@/src/components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <CustomThemeProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
